<?php

namespace App\Processor;

use Stichoza\GoogleTranslate\GoogleTranslate;
use App\Logger\Logger;

use TextAnalysis\Tokenizers\GeneralTokenizer;
use TextAnalysis\Analysis\FreqDist;
use TextAnalysis\Documents\TokensDocument;
use TextAnalysis\Filters\LowerCaseFilter;
use TextAnalysis\Filters\StopWordsFilter;
use TextAnalysis\Filters\NumbersFilter;
use TextAnalysis\Filters\PunctuationFilter;
use TextAnalysis\Filters\CharFilter;
use TextAnalysis\Filters\QuotesFilter;
use TextAnalysis\Filters\SpacePunctuationFilter;

class NewsFetchProcessor
{
    private GoogleTranslate $translator;    

    // CONFIGURATION OF PARAMETERS USED IN CALCULATIONS
    private $FREQDIST_FREQUENCY_KEYSIZE = 4; // MINIMUM LENGTH A TERM MUST HAVE TO BE CONSIDERED IN THE REPETITION FILTER
    private $FREQDIST_FREQUENCY_QTDE = 4; // MINIMUM NUMBER OF TIMES THE TERM MUST APPEAR TO BE CONSIDERED IN THE REPETITION FILTER

    private $RAKE_VALUATIONSIZE = 5; // NUMBER OF TERMS CONSIDERED IN THE SENTENCE FORMULATION FUNCTION
    private $RAKE_KEYWORDSCORE = 100; // THRESHOLD USER TO CONSIDER EFFECTIVE RETURN IN RAKE FUNCTION
    private $RAKE_TOKENS_MIN = 100; // MIN NUMBER OF TOKENS FOR TEXT
    private $RAKE_TOKENS_MAX = 500; // MAX NUMBER OF TOKENS FOR TEXT

    // CONTROLS THE VALUE AND WEIGHT OF EACH VARIABLE USED IN THE CALCULATION
    private $TEXTVALUATION_INDEXES = array(
        'RAKE_SCORE'             => array('index' => 0.15),
        'RAKE_QT_SCORE_ORIGINAL' => array('index' => 0.01),
        'RAKE_QT_TOKENS'         => array('index' => 0.03),
        'RAKE_QT_TOKENS_EXCESS'  => array('index' => -0.3), // NEGATIVE
        'RAKE_QT_SCORE_FILTER'   => array('index' => 0.01),
        'RAKE_SCORE_SUCCESS'     => array('index' => 5),
        'FREQDIST_SCORE'         => array('index' => -20),         
    );

    public function __construct(
        private array   $config, 
        private Logger  $logger
    ){
        $this->translator = new GoogleTranslate();
        $this->translator->setSource($config['translate']['source']);
        $this->translator->setTarget($config['translate']['target']);
    }

    public function normalize(array $raw): ?array
    {
        if (empty($raw['title']) || empty($raw['link'])) {
            return null;
        }

        $title = $this->translateTitle($raw['title']);    
        $this->logger->info('Translated: [' . $title . ']');
        $score = $this->checkRake($title);
        $this->logger->info('Score: [' . $score . ']');

        return [
            'title'           => $title,
            'title_pt'        => $raw['title'],
            'date'            => $raw['date']   ?? date('Y-m-d H:i:s'),
            'link'            => $raw['link'],
            'img'             => $raw['img']  ?? null,
            'description'     => $raw['description'] ?? null,
            'score'           => $this->checkRake($title)
        ];
    }

    public function normalizeMany(array $items): array
    {
        $normalized = array_map([$this, 'normalize'], $items);

        return array_values(array_filter($normalized));
    }

    private function translateTitle(string $title): string
    {
        try {
            return trim($this->translator->translate($title)) ?? $title;
        } catch (\Exception $e) {
            $this->logger->error('Translation failed: ' . $e->getMessage());
            return $title;
        }
    }

    private function checkRake($text = '') {
        // LOADS LIST OF IGNORED TERMS IN THE ORIGINAL TEXT
        $stopwords = array_map('trim', file(__DIR__ . DS . 'stop-words.txt'));
        
        // - ELIMINATES LINE BREAKS, AS WELL AS UNNECESSARY PUNCTUATION
        // - GENERATES THE TOKEN FOR ANALYSIS
        $text = (new SpacePunctuationFilter([':', '\/']))->transform($text);
        $tokens = (new GeneralTokenizer(" \n\t\r"))->tokenize($text);        
        
        // APPLIES RAKE METHOD THROUGH SEVERAL CONTENT SANITATION FILTERS
        $tokenDoc = new TokensDocument($tokens);
        $tokenDoc->applyTransformation(new LowerCaseFilter())
                ->applyTransformation(new StopWordsFilter($stopwords), true)
                ->applyTransformation(new PunctuationFilter(['@', ':', '\/', ';']), true)
                ->applyTransformation(new QuotesFilter())
                ->applyTransformation(new NumbersFilter())
                ->applyTransformation(new CharFilter(), true);

        // EVALUATION CALCULATION CONSIDERING AS A TARGET PHRASES WITH A DEFINED NUMBER OF TERMS IN A VARIABLE
        $rake = rake($tokenDoc->toArray(), $this->RAKE_VALUATIONSIZE);
        // APPLIES A FILTER TO THE LIST OF TERMS GENERATED BY THE RAKE FUNCTION
        $final_array = array_filter($rake->getKeywordScores(), function ($var) {
                return $var >= $this->RAKE_KEYWORDSCORE;
        });

        // TOTAL VALUE OF THE VALUATION PERFORMED USING THE FILTERED RAKE FUNCTION
        $this->TEXTVALUATION_INDEXES['RAKE_SCORE']['value'] = array_sum($final_array);
        
        // NUMBER OF RECORDS CALCULATED IN THE ORIGINAL RAKE FUNCTION
        $this->TEXTVALUATION_INDEXES['RAKE_QT_SCORE_ORIGINAL']['value'] = count($rake->getKeywordScores());        

        // NUMBER OS WORDS USER AFTER THE FILTER
        $this->TEXTVALUATION_INDEXES['RAKE_QT_TOKENS']['value'] = count($rake->getTokens());        

        // SURPLUS CALCULATION IS APPLIED IF THE TOKEN QUANTITY IS LESS THAN THE MINIMUN OF GREATER THE THE MAXIMUM INDICATED
        if ($this->TEXTVALUATION_INDEXES['RAKE_QT_TOKENS']['value'] < $this->RAKE_TOKENS_MIN) {
            $rake_qt_tokens = ($this->RAKE_TOKENS_MIN - $this->TEXTVALUATION_INDEXES['RAKE_QT_TOKENS']['value']);
        } else if ($this->TEXTVALUATION_INDEXES['RAKE_QT_TOKENS']['value'] > $this->RAKE_TOKENS_MAX) {
            $rake_qt_tokens = ($this->TEXTVALUATION_INDEXES['RAKE_QT_TOKENS']['value'] - $this->RAKE_TOKENS_MAX);
        } else {
            $rake_qt_tokens = 0; // SET THE VARIABLE DO ZERO SO IT DOESNT COUNT IN THE DISCOUNT FUNCTION
        }
        $this->TEXTVALUATION_INDEXES['RAKE_QT_TOKENS_EXCESS']['value'] = $rake_qt_tokens;
        unset($rake_qt_tokens);

        // NUMBER OF RECORDS CONSIDERED IN THE RAKE FUNCTION
        $this->TEXTVALUATION_INDEXES['RAKE_QT_SCORE_FILTER']['value'] = count($final_array);

        // SUCCESS INDEX. CALCULATES THE PERCENTENGE OF THE RAKE FUNCTION CONSIDERED POSITIVE
        $this->TEXTVALUATION_INDEXES['RAKE_SCORE_SUCCESS']['value'] = ($this->TEXTVALUATION_INDEXES['RAKE_QT_SCORE_FILTER']['value'] / $this->TEXTVALUATION_INDEXES['RAKE_QT_SCORE_ORIGINAL']['value']);        

        // RESULT FROM THE FREQUENCY DISTRIBUTION FUNCTION. SUMS THE NUMBER OF EXCESS TOKENS
        $this->TEXTVALUATION_INDEXES['FREQDIST_SCORE']['value'] = $this->checkFreqDist($tokenDoc->toArray());
        
        // FINAL SCORE CALCULATION
        $rake_final_score = 0;
        foreach ($this->TEXTVALUATION_INDEXES as $key => $item) {                                
            $rake_final_score += $item['index'] * $item['value'];
        }
        
        return $rake_final_score;
    }

    /*
        USING FREQUENCY DISTRIBUTION ANALYSIS
        IDENTIFIES AND SCORES REPEATED WORDS IN THE TEXT
    */    
    function checkFreqDist($tokens) {
        $this->FREQDIST_FREQUENCY_QTDE = 3; // ORIGINAL VALUE

        // FREQUENCY ANALYSER. DIVIDES THE TEXT INTO WORDS AND QUANTIFIES THE ITEMS
        $freqDist = new FreqDist($tokens);
        
        // TOTAL NUMBER OF TERMS
        $freq_total_totens = $freqDist->getTotalTokens();
        
        // TOTAL NUMBER OF UNIQUE TERMS - EXCLUDES REPETITIONS
        $freq_unique_tokens = $freqDist->getTotalUniqueTokens();

        // CALCULATE THE LIMIT OF REPETITIONS ACCEPTED IN THE FILTER
        if ($freq_total_totens > $this->RAKE_TOKENS_MIN) {
            $this->FREQDIST_FREQUENCY_QTDE = ($freq_total_totens * $freq_total_totens) / ($freq_unique_tokens * ($freq_total_totens - $freq_unique_tokens));                    
        }
        
        // CONSIDER ONLY TERMS WITH MORE THAN SPECIFICS DIGITS THAT APPER MORE.
        $arrayFreq = array_filter($freqDist->getKeyValuesByFrequency(), function ($value, $key) {
                return strlen($key) >= $this->FREQDIST_FREQUENCY_KEYSIZE && $value >= $this->FREQDIST_FREQUENCY_QTDE;
        }, ARRAY_FILTER_USE_BOTH);
        return (count($arrayFreq) / $freq_unique_tokens) * array_sum($arrayFreq);
    }
}
